services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./app:/app/app  # For development (optional)
      - ./db:/app/db
      - certbot-data:/app/certbot  # Persist certbot data
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - DUCKDNS_SUBDOMAIN=${DUCKDNS_SUBDOMAIN}
      - EMAIL=${EMAIL}
      - DATABASE_URL=sqlite3:/app/db/chores.db # Or set other env vars for email, etc.
volumes:
  certbot-data: # Declare the named volume